### ISSUE TITLE
Rollback database on handle_package_files() errors

### ISSUE THREAD

**Issue by benjamb** [mamba-org/quetz#103]
https://github.com/mamba-org/quetz/blob/5ec70ae9935fbd0dfc42c72b2ebb59a1f30f8ccd/quetz/main.py#L627-L631

If any of the pkgstore operations fail, we should likely then revert changes made to the database. A 'force' would likely also fix this issue should it ever occur.

**Comment by wolfv** [comment]
probably similar to #84 ?

**Comment by benjamb** [comment]
> probably similar to #84 ?

Ah yes, more caffeine is required I think.
