### ISSUE TITLE
[feature-request] auto-transmute

### ISSUE THREAD

**Issue by dhirschfeld** [mamba-org/quetz#111]
The new `.conda` package format is more efficient than the old `.bz2` format.

The [`conda-package-handling`](https://github.com/conda/conda-package-handling) library can ***transmute*** `.bz2` packages into the new `.conda` format. To make the `quetz` server as fast and efficient as possible it would be great to be able cache *transmuted* packages if the source was a `.bz2` package so that `quetz` only served `.conda` packages.

**Comment by wolfv** [comment]
Yes we will add this capability to our mamba (C++) library soon (and also use it in boa). 
I'll work on this this week :)

**Comment by wolfv** [comment]
we might be able to implement this with plugins now. what do you think @btel?

**Comment by wolfv** [comment]
we have this now in master :)

**Comment by wolfv** [comment]
improvements are coming in #244
