### ISSUE TITLE
channel names should be case insensitive

### ISSUE THREAD

**Issue by wolfv** [mamba-org/quetz#163]
Currently if I have a `RoboStack` channel, it's different from `robostack`. However, I think (also for security reasons) that those names should be case insensitive and both should point to the same channel.
Same for user names etc.

**Comment by wolfv** [comment]
We can probably rewrite URL's in nginx if we have to.

**Comment by btel** [comment]
lets do it at the database level, it's better than patching with nginx ;-)

**Comment by wolfv** [comment]
I think anaconda.org ignore case at the URL level though:

https://conda.anaconda.org/CONDA-FORGE/linux-aarch64/repodata.json

works.

Not sure how to properly implement that since we're serving these files from the filesystem.

**Comment by adriendelsalle** [comment]
If we want to handle fine-grained permissions for pulling, we should hide packages that are not available to users without the required access level (both is the repodata.json file and the packages themselves).

It would require a database filter and a different machinery than serving static files from a root.
I think it will be also needed to be able to reproduce an environment at a given timestamp.

**Comment by btel** [comment]
@adriendelsalle indeed that's an important issue, it's possible that we do not respect the permission levels when serving the repodata.json and package files. Would you mind openning a new issue for this?

@wolfv indeed, we will also need to apply some pre-processing on the static file endpoints. I was thinking rather about the API endpoints, which should be adapted as well.

**Comment by wolfv** [comment]
Even with fine grained permissions, we should probably have a default cache of simple static files for the majority of users with no elevated privileges. Those that access our server with a token would get special treatment. 
Or we decide to not care about the "static files" approach for the moment, then we can just implement this in a FastAPI handler.

**Comment by adriendelsalle** [comment]
> Would you mind openning a new issue for this?

@btel I think it is related to #81 and #54

**Comment by btel** [comment]
cool, thanks for the pointer @adriendelsalle
