### ISSUE TITLE
GitHub-style search syntax

### ISSUE THREAD

**Issue by wolfv** [mamba-org/quetz#17]
Where people can filter with `author:wolfv is:pr`...

We could do labels like:

`channel:conda-forge version:>0.2.5`

or stuff like that

**Comment by wolfv** [comment]
We could use codemirror or monaco for custom auto-completion.

https://github.com/microsoft/monaco-editor/issues/2009

https://discuss.codemirror.net/t/single-line-codemirror/195/3

**Comment by btel** [comment]
link to the relevant section of github API docs:

https://docs.github.com/en/free-pro-team@latest/rest/reference/search#constructing-a-search-query

**Comment by wolfv** [comment]
done cc @madhur-tandon :)
