### ISSUE TITLE
mirror: select / unselect packages

### ISSUE THREAD

**Issue by wolfv** [mamba-org/quetz#170]
It would be cool to have the functionality to select / unselect specific packages. This might be useful if some packages can only be distributed on e.g. anaconda.org

**Comment by btel** [comment]
as discussed on gitter, this functonality should be configured via `metdata` field in POST /api/channels endpoint

**Comment by wolfv** [comment]
@madhur-tandon this is done, right?

**Comment by madhur-tandon** [comment]
Yeah, if this issue refers to the `whitelist` / `blacklist` stuff while creating a mirror, then yes, it's done.
