### ISSUE TITLE
[Doc request] Roadmap for going live

### ISSUE THREAD

**Issue by corneliusroemer** [mamba-org/quetz#172]
I've come across this project as what seems to be the best attempt to work around Anaconda's change in TOS moving away from offering free hosting of conda packages.

It appears as though Quetz is not yet in production, can you confirm? This is not explicitly stated in the Readme, so I just want to make sure I'm not being stupid, not finding the link.

Maybe it'd be a good idea to be transparent about your rollout plans, how far away are you from going live? Good luck, I'm happy to see someone is working on breaking Anaconda's unhealthy monopoly on conda package hosting.

**Comment by SylvainCorlay** [comment]
> the best attempt to work around Anaconda's change in TOS moving away from offering free hosting of conda packages.

This project does not really have to do with the Anaconda terms of services (also, I don't think that the recent change really has much impact on e.g. conda-forge and other open-source hosting). 

However, deploying an instance of a Quetz server is a good way to host conda packages if you are unhappy with other solutions.

> It appears as though Quetz is not yet in production, can you confirm? This is not explicitly stated in the Readme, so I just want to make sure I'm not being stupid, not finding the link.

Quetz is a open-source project that implements a conda package server. There is not a public-facing deployment of Quetz at the moment - if that is the question, besides test instances used for development and testing.

> Maybe it'd be a good idea to be transparent about your rollout plans, how far away are you from going live?

Some people have plans for public-facing hosting of Quetz instances, but it is somewhat independent from the software project.

**Comment by btel** [comment]
hi @corneliusroemer, if you plan to deploy your instance of quetz, we have some docs that may help: https://quetz.readthedocs.io/en/latest/

Please don't hesitate to ask if something is not clear, or find some missing information.
