### ISSUE TITLE
Store and expose metrics

### ISSUE THREAD

**Issue by adriendelsalle** [mamba-org/quetz#174]
It could be great to store and expose metrics for monitoring activity, using for instance `prometheus` timeseries database.

- to see number of downloads for package(s) or channel(s)
- to detect abnormal use/monitor user activity
- enforce rules for a max number of push/pulls per minutes etc?
- use `grafana` for nice dahboards!
- etc.

Just a draft, feel free to contribute!

**Comment by wolfv** [comment]
we got this now :)
