### ISSUE TITLE
api key should have no underscores to be used as token with conda/mamba

### ISSUE THREAD

**Issue by sanzoghenzo** [mamba-org/quetz#231]
Now that I correctly set up my quetz server with google oauth, I'm having trouble installing packages from it.

- quetz runs on a development server that has SSL enabled (nginx proxy to quetz http);
- I logged in at my destkop using the google oauth;
- I got the key and exported to `QUETZ_API_KEY` in my WSL;
- I successfully published a package (let's call it `my-package`) to one of the private channels I created;
- running `mamba install -c $MY_CHANNEL_URL/my-package` fails 

```
channels/staging/linux-6 [====================] (00m:00s) 401 Failed
channels/staging/noarch  [====================] (00m:00s) 401 Failed
conda-forge/linux-64     [<=>                 ] (00m:00s) 15  B / ?? (36.00  B/s)
conda-forge/noarch       [<=>                 ] (00m:00s) 15  B / ?? (36.00  B/s)
pkgs/main/linux-64       [<=>                 ] (00m:00s) 434  B / ?? (1.04 KB/s)
```

(side note: the linux-64 channel is empty, and it returns `{"detail":"staging/linux-64 not found"}`, will it be a problem like #96 ? the same is true also for all the other platforms) 

- if I try to `mamba search -c $MY_CHANNEL_URL/my-package`:

```
Loading channels: failed

CondaHTTPError: HTTP 401 UNAUTHORIZED for url <https://conda.sws-digital.com/channels/staging/linux-64/repodata.json>
Elapsed: 00:00.258542

The credentials you have provided for this URL are invalid.

You will need to modify your conda configuration to proceed.
Use `conda config --show` to view your configuration's current state.
Further configuration help can be found at <https://conda.io/docs/config.html>.
```

what should I pass to mamba/conda to set the credentials?

**Comment by wolfv** [comment]
good question! I think we need to better test this. 

I think when you generate an API key with the correct permissions, you can add the token in ~/.continuum/anaconda-client/tokens/

I have a token for anaconda.org installed there. It's filename is: 

`https%3A%2F%2Fapi.anaconda.org.token`

and it contains just the token.

The other option is to set up HTTP basic auth through nginx or fastapi, and then configure the credentials in the `.condarc`.

**Comment by wolfv** [comment]
Obviously the idea is to adjust the filename to match your URL :+1: 

This is from the conda manual (https://docs.anaconda.com/anacondaorg/user-guide/tasks/work-with-accounts/)

```
   conda config --add channels https://conda.anaconda.org/t/<token>/<channel>

Add a channel with a token and a label::

   conda config --add channels https://conda.anaconda.org/t/<token>/<channel>/label/<labelname>


NOTE: Replace ``<token>`` with your token string,``<channel>`` with the channel name,
``<labelname>`` with the label name used in :ref:`cloud-accounts-generate`.
```

**Comment by sanzoghenzo** [comment]
thanks @wolfv ! I didn't see the /t/ endpoint in the swagger UI, so I thought it wasn't possible...
Now that I discovered the `CondaTokenMiddleware`, everything makes sense.

I now have a problem, i think it's conda's fault: if my key has underscores, and when I run `mamba install` or `mamba search` (or `conda`) the part after the `_` gets moved after the domain and before the `/t/`, i.e.
`https://"$MY_URL"/t/XXXXXXXX_YYYYYY/channels/staging`
becomes 
`https://"$MY_URL"_YYYYYY/t/XXXXXXXX/channels/staging`
and obviously a `CondaHTTPError: HTTP 000 CONNECTION FAILED` is returned

I don't use anaconda, so I don't have any token with them, but could it be that their tokens never contain underscores?

**Comment by sanzoghenzo** [comment]
OK, I can confirm that an api key without underscores works!
I don't know if a simple `token_urlsafe(32).replace("_", "-")` is good enough or it it's better to call the function until there's no underscores in the output string...

Any thoughts?

**Comment by wolfv** [comment]
yeah i don't really like our API tokens.

I think we could restrict them to `[a-zA-Z0-9\-]` or something like that.

The anaconda.org tokens have a format of `WO-XXXX-XXXXXXX-XXXXXXX-XXXXX` or similar, the first two letters are the initials of the organization.

Do you want to put in a PR to make nicer tokens?

**Comment by sanzoghenzo** [comment]
> yeah i don't really like our API tokens.
> 
> I think we could restrict them to `[a-zA-Z0-9\-]` or something like that.
> 
> The anaconda.org tokens have a format of `WO-XXXX-XXXXXXX-XXXXXXX-XXXXX` or similar, the first two letters are the initials of the organization.

that is more like an UUID than a secure token;
I don't feel like it's the right choice (fixed `-` position and fixed organization letters leaves us with 23 random bytes), but I am by no means a security expert!

Even the random UUUID4 has only 128bits, and 6 of them are fixed; the secrets python documentation states that:
> As of 2015, it is believed that 32 bytes (256 bits) of randomness is sufficient for the typical use-case expected for the secrets module

Maybe we can simply swap to `token_hex`? that way we only have `[0-9a-f]` chars, but if we keep the 32 bytes length there shouldn't be any problem, and the resulting string will be 64 characters long.

Or I can settle with the "generate `token_urlsafe` until there are no underscores"...
Which one do you prefer?

> Do you want to put in a PR to make nicer tokens?

OK!
Should I add validation on the ApiKey model, also? this will be a breaking change, so I'm asking for permission here 😉

**Comment by wolfv** [comment]
Cool :)

I think limiting ourselves to hex is also not great.

How about this snippet from the Python secrets module:

https://docs.python.org/3/library/secrets.html#recipes-and-best-practices

```
import string
import secrets
alphabet = string.ascii_letters + string.digits
password = ''.join(secrets.choice(alphabet) for i in range(8))
```

**Comment by sanzoghenzo** [comment]
I didn't read through the end of the page 😅 

great, I will use that!

**Comment by wolfv** [comment]
sounds good. Also yes to any validation updates, I am happy with breaking changes.
