### ISSUE TITLE
Maximum channel size is in bytes

### ISSUE THREAD

**Issue by wolfv** [mamba-org/quetz#290]
I think the maximum channel size is currently in bytes. If we are using a regular integer, that limits the maximum allowed channel size to 2 Gigabyte which is not that much. 

We could decide to interpret the number as Megabyte.

What do you think @btel?

**Comment by btel** [comment]
😄 yes, that might be an issue. good catch!

**Comment by wolfv** [comment]
@madhur-tandon do you want to have a stab at this?

**Comment by madhur-tandon** [comment]
The only thing is, do we want to constraint things to be as an Integer then?

**Comment by btel** [comment]
isn't it already the case? the pydantic model and the db model should only accept integers

**Comment by madhur-tandon** [comment]
yes, but, we would want to change that to float right?
because we divide by 1e6 to get Megabytes

**Comment by btel** [comment]
no, I don't think so. 1MB of resolution should be enough.
