### ISSUE TITLE
Investigate memory leak in channel sync

### ISSUE THREAD

**Issue by wolfv** [mamba-org/quetz#332]
Somewhere we got a memory leak when syncing conda-forge. 

Up to 1 Gb per sync is leaked. 

Maybe it's in the current_repodata.json generation?

**Comment by btel** [comment]
caused by a leak in adlfs library: https://github.com/dask/adlfs/pull/173

**Comment by wolfv** [comment]
yep. The last "leak" we need to fix is to properly clean up after the conda-build current_repodata generation, because conda caches a couple of things.

**Comment by btel** [comment]
this is already done in #345

**Comment by wolfv** [comment]
ok let's close this for now then. With our new grafana infrastructure we should see this coming, if it happens again.
