### ISSUE TITLE
Process for reporting security bugs

### ISSUE THREAD

**Issue by stevenryoung** [mamba-org/quetz#394]
What is the preferred process of the maintainers for reporting security bugs and patches? Can I just do that with Issues/Pull Requests here? Or does that need to be done by email? If by email, who?

**Comment by wolfv** [comment]
I think since there is no public instance of quetz nor any paying customer as of now, it's fine to post security bugs as issue here. Did you find anything?

Otherwise, feel free to email me in private (email is in my github profile)

**Comment by stevenryoung** [comment]
Just posted #395 . Closing this. Thanks!
