### ISSUE TITLE
Frontend: only serve static files below frontend dir

### ISSUE THREAD

**Issue by wolfv** [mamba-org/quetz#396]
This is currently fixed by checking for `..` but I think we can find a cleaner solution.

**Comment by stevenryoung** [comment]
`os.path.commonpath()` seems like it could make a more robust solution (in the case that quetz should ever serve a file with two consecutive periods or expect a relative path but under the `frontend_dir`). Just check if the common path is equal to the `frontend_dir`, and make a decision based on that. https://docs.python.org/3/library/os.path.html#os.path.commonpath

**Comment by wolfv** [comment]
Yes, indeed! That looks like a good function to use.

**Comment by wolfv** [comment]
Thanks @stevenryoung for tackling this!
