### ISSUE TITLE
Make new release

### ISSUE THREAD

**Issue by beenje** [mamba-org/quetz#397]
Hello!

Latest release is from July 2020. I think it would be nice to make a new one.
That would also publish a docker image with the same tag: https://hub.docker.com/r/mambaorg/quetz

By the way, I'm not sure to understand the tag convention. There is a mix of client / frontend vx.x.x.

Note that with the current GitHub workflow, the git tag will be used to tag the docker image.

**Comment by wolfv** [comment]
yep, we're looking into making a release soonish.

**Comment by baszalmstra** [comment]
Any update on when this might happen? Very much looking forward to this! :)
