### ISSUE TITLE
Try to cache repodata.json for proxy channels

### ISSUE THREAD

**Issue by beenje** [mamba-org/quetz#414]
Currently the repodata.json and current_repodata.json files aren't cached for proxy channels: https://github.com/mamba-org/quetz/blob/bfe0af1c3e668de0948b2b3cb093cd451d9a6493/quetz/tasks/mirror.py#L67

The file is streamed every time a client requests it. We could cache it locally to avoid downloading it for every clients.
Anaconda sets max-age to 1200 seconds in the cache-control header.

Maybe something similar is already done for mirror channels?

**Comment by wolfv** [comment]
Yes, we do also set cache control headers. 
I think it might be even better to simply redirect? Since that would set all headers properly. Otherwise we should forward headers and make sure that we get a gzip-encoded response.

**Comment by beenje** [comment]
I'd like to redirect, but that needs to be a local file. We can't redirect to the original url as the point of using a proxy channel is probably that clients are behind a firewall and can't access the original channel.

**Comment by beenje** [comment]
This was implemented in https://github.com/mamba-org/quetz/pull/413
Closing.
