### ISSUE TITLE
Cannot connect to repo.mamba.pm server when creating a Quetz environment

### ISSUE THREAD

**Issue by ernstluring** [mamba-org/quetz#432]
When I try to create a quetz environment by running `mamba env create -f environment.yml` I get the following error:
`RuntimeError: Download error (7) Couldn't connect to server [https://repo.mamba.pm/conda-forge/noarch/repodata.json]
    Failed to connect to repo.mamba.pm port 443: Connection refused`

https://repo.mamba.pm seems to be down. Is there a way to easily fix this?

**Comment by wolfv** [comment]
yep, just change to `conda-forge`.

**Comment by ernstluring** [comment]
Yes that works. Thanks for the quick response!
