### ISSUE TITLE
https redirect

### ISSUE THREAD

**Issue by baszalmstra** [mamba-org/quetz#445]
I'm hosting a quetz server on Google Cloud App Engine. This provides us with a hosting solution that is easy to use and easy to scale and update and we get https out of the box. I'm doing this through the use of a docker container very similar to the one in this repository. This requires the "flex" environment. A problem with that is that `http` request are not automatically forwarded to `https`. I found that starlette has a simple solution for this called [`HTTPSRedirectMiddleware`](https://www.starlette.io/middleware/#httpsredirectmiddleware). I can make a PR to integrate this into quetz but I was wondering if that is indeed the way forward?

**Comment by wolfv** [comment]
Solved by your PR. Thanks again!
