### ISSUE TITLE
How to mamba install package from private channel?

### ISSUE THREAD

**Issue by baszalmstra** [mamba-org/quetz#450]
I've got quetz setup properly. I've got an API key that I can use to query the server with. But how can I use `mamba install` to get packages from private channels? I figured out I have to pass the `X-Api-Key` header, but how can I configure `mamba` or an `environment.yml` to do so?

**Comment by wolfv** [comment]
great!

Excellent question :) We don't have a streamlined way yet, unfortunately!

You can use an API Key as a "Token". The authentication works by adding a `/t/API-KEY...` to the URL. 

To add a token manually you can place it in `.continuum/anaconda-client/tokens`. There you should put a file that has your URL-encoded domain as name + ".token", and contains the token. 

E.g. the file I have in that folder is called `https%3A%2F%2Fapi.anaconda.org.token` and has as contents only the token.

This is obviously not great. I am not sure if the conda-token package makes this nicer (it seems to be closed source). 

Anyways, we should make this part of mamba's functionality. Also we should find a better location than `~/.continuum`...

**Comment by baszalmstra** [comment]
I couldn't get the `.token` file to work for my own server. Any way I can debug this?

Adding the `/t/API-KEY` in front of the path of the URL does work, so I'll hack something around that for now. :)

**Comment by baszalmstra** [comment]
So after digging around in the conda source code I finally figured out I have to write the token to: `~/.config/binstar/` instead of `.continuum/anaconda-client/tokens`. This works for `conda` but `mamba`raises an error:

```
$ mamba install -c https://<server-url>/get/robostack ros-noetic-roslib
...
RuntimeError: Download error (3) URL using bad/illegal format or missing URL [https://<server-url>/t/<api-key>
    /get/robostack/noarch/repodata.json]
```

It looks like an enter is added after the API key??

**Comment by wolfv** [comment]
@baszalmstra can you remove the trailing newline in the file? Otherwise, I'll have to take a look where we need to `strip` in the mamba source code ... would be cool to open an issue over there.

**Comment by baszalmstra** [comment]
Never mind, there was indeed a newline at the end of the file. 🤦‍♂️
