### ISSUE TITLE
Postgresql integration crashes on restart of quetz

### ISSUE THREAD

**Issue by j-montforts** [mamba-org/quetz#453]
I started a Postgresql docker container locally and started my quetz in another docker locally. First time the quetz container gets started it creates the quetz. tables in my database.
Second time I start my quetz container I get the following error :

sqlalchemy.orm.exc.FlushError: New instance <Identity at 0x7fd7591aa3d0> with identity key (<class 'quetz.db_models.Identity'>, ('dummy', '0'), None) conflicts with persistent instance <Identity at 0x7fd758eb8a90>

**Comment by adriendelsalle** [comment]
Thanks for reporting this bug. It looks like we should use a merge to avoid this.

**Comment by wolfv** [comment]
@j-montforts I guess you are starting quetz with `--dev` so that dummy users are created?
We're not really testing postgresql with `--dev` mode currently.

**Comment by j-montforts** [comment]
Removing --dev solved the probleem indeed. Thanks.
