### ISSUE TITLE
Add 'appdirs' and `toml` as dependencies for quetz_client

### ISSUE THREAD

**Issue by venabled** [mamba-org/quetz#460]
Wanted to use quetz_client on ARM64 independently of the main quetz package (as that had some dependencies that aren't available on aarch64 via conda-forge), and noticed that uploading the built package failed due to not having `appdirs` / `toml` in my environment.

**Comment by janjagusch** [comment]
The quetz-client is now a standalone Conda package:  https://github.com/mamba-org/quetz-client
