### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by janjagusch** [mamba-org/quetz#468]
Thanks for maintaining `quetz`!

We'd like to use the new GCS backend introduced in https://github.com/mamba-org/quetz/pull/449 but there hasn't been a new release since then. Could you please make a new release?

Thanks a lot in advance!

**Comment by wolfv** [comment]
Ok, released 0.2.0 :)

**Comment by wolfv** [comment]
Btw. if you could take care of the conda-forge release, that would be great! 
We might have to adjust the dependencies. Please take a look at https://github.com/mamba-org/quetz/blob/master/environment.yml
