### ISSUE TITLE
Pull-mirror functionality to experiment with bot ideas

### ISSUE THREAD

**Issue by wolfv** [mamba-org/quetz#47]
It would be good to have a way to fill the quetz package server with an initial set of packages that can be selected through selectors and downloaded e.g. from the anaconda.org repo.

The quetz server should probably have facilities to periodically scrape the endpoint for new package versions.

cc @beckermr

**Comment by beckermr** [comment]
cc @CJ-Wright too

**Comment by ericdill** [comment]
might want to have a look at [conda-mirror](github.com/conda-tools/conda-mirror)

**Comment by btel** [comment]
See proposal 3 in the document: https://hackmd.io/kgifxnZ7SFupZkWjwsUxnw

An alternative implementation of the mirror (push-mirror) is discussed in #43

**Comment by wolfv** [comment]
We have this in quetz now, and it works pretty smooth!
