### ISSUE TITLE
Problem while trying to proxy channels

### ISSUE THREAD

**Issue by j-montforts** [mamba-org/quetz#477]
We've added a proxy for robostack using the swagger interface :
{
  "name": "proxy-robostack",
  "private": true,
  "mirror_channel_url": "https://conda.anaconda.org/robostack",
  "mirror_mode": "proxy"
}

When trying to get a package, we get no results :
conda install --strict-channel-priority -c https://<URL>/get/proxy-robostack ros-noetic-nav-msgs

Using a mirror instead of proxy, all packages are downloaded, which we do not want.

**Comment by wolfv** [comment]
Did you try with `private: false`? 
And if you try to access the files directly, do you see any log messages?

e.g. `https://myproxy.com/get/proxy-robostack/linux-64/repodata.json` OR some particular package `https://myproxy.com/get/proxy-robostack/linux-64/somepkg.tar.bz2`

**Comment by wolfv** [comment]
What kind of error are you seeing? What is the response of the server?

**Comment by wolfv** [comment]
Hi @j-montforts there was a bug that was related to the `noarch` channel and `proxy` channels. That bug is fixed in the latest quetz release. Hopefully it also fixes your issues.
