### ISSUE TITLE
Change `/get` URL structure to make it compatible with Conda config

### ISSUE THREAD

**Issue by JanJaguschQC** [mamba-org/quetz#492]
Hi, thanks for maintaining quetz! 👍 

We're trying to configure Conda, such that it can communicate with our quetz server, without having to provide the token for every install.

This is the `.condarc` we're using:

```
custom_channels:
  general: https://MYHOST/t/MYTOKEN/get/
channels:
  - general
  - conda-forge
```

However, when executing `mamba search my-private-package`, we get the following error:

```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://MYHOST/get/t/MYTOKEN/general/noarch/repodata.json
```

Notice how it says `https://MYHOST/get/t/MYTOKEN/general` instead of `https://MYHOST/t/MYTOKEN/get/general`.

This is due to [how Conda creates the URL with credentials](https://github.com/conda/conda/blob/edb5737bd877ce6334e2e9b7f9cbf40103edb229/conda/models/channel.py#L205-L226), which is later used to [fetch the repodata](https://github.com/conda/conda/blob/edb5737bd877ce6334e2e9b7f9cbf40103edb229/conda/core/subdir_data.py#L375-L379).

In a nutshell, the original URL is parsed into a `Channel` object with the following structure:

```py
{'scheme': 'https', 'auth': None, 'location': 'MYHOST/get', 'token': 'MYTOKEN', 'name': 'general', 'platform': 'noarch', 'package_filename': None, '_Channel__canonical_name': 'general'}
```

And the URL with credentials is put together like this:

```py
{self.location}/t/{self.token}/{self.name}/{self.platform}
```

I would say the easiest fix is to adjust the Quetz URL to accept `MYHOST/get/t/MYTOKEN/CHANNEL` instead of/additional to `MYHOST/t/MYTOKEN/get/CHANNEL`. Other solutions would require changing the Conda parser and the URL generator, which will be much more difficult.

It might even be enough to change [this regular expression](https://github.com/mamba-org/quetz/blob/4d88b4695166d310823a48e81e025983846afd05/quetz/main.py#L142) to also match the token when it's not at the beginning of the string.

If that's something you'd like to see fixed, I'd be glad to put together a PR.

**Comment by wolfv** [comment]
Is it possible to configure nginx or another reverse proxy to forward another subdomain (such as `repo.mydomain.com` to `mydomain.com/get/{...}` ? That's how we and anaconda are doing it, essentially.

**Comment by baszalmstra** [comment]
Im using a token file as described here: https://github.com/mamba-org/quetz/issues/450

**Comment by JanJaguschQC** [comment]
> Im using a token file as described here: #450

Thanks for the pointer, @baszalmstra. I managed to make Conda find the token file, however, this seems to [just create another Channel object](https://github.com/conda/conda/blob/2e081b5ab648d415a59dea458a3d695ecc9ec837/conda/gateways/connection/session.py#L131-L141), which produces the same incorrect URL as in my example above.

Do you have a working example, where you use Quetz together with a `.condarc` and are able to `mamba install`?

**Comment by JanJaguschQC** [comment]
> Is it possible to configure nginx or another reverse proxy to forward another subdomain (such as `repo.mydomain.com` to `mydomain.com/get/{...}` ? That's how we and anaconda are doing it, essentially.

Thanks, @wolfv! Do you happen to have an Nginx config file that you could share here?

**Comment by JanJaguschQC** [comment]
This nginx config worked for us, assuming you have quetz running on port 8000:

```
server {
    listen 80;
    listen [::]:80;
    client_max_body_size 200M;
    access_log /var/log/nginx/reverse-access.log;
    error_log /var/log/nginx/reverse-error.log;
     location /get/t/ {
        rewrite ^/get/t/([^/]+)/([^/]+)/(.*)$ /t/$1/get/$2/$3 break;
        proxy_pass http://127.0.0.1:8000;
    }
    location / {
        proxy_pass http://127.0.0.1:8000;
    }
}
```

**Comment by wolfv** [comment]
@JanJaguschQC we have something like this:

```
        server_name repo.mamba.pm;
        rewrite ^/(.*)$ /get/$1 break;
```

but that only works if you have access to subdomains :)

**Comment by JanJaguschQC** [comment]
I'm going ahead and close this, as wrapper an nginx server around quetz solved the issue for us.
