### ISSUE TITLE
Think about cache proxying packages

### ISSUE THREAD

**Issue by wolfv** [mamba-org/quetz#51]
One interesting idea that came up was to configure quetz in a way that it proxies the (requested) packages for e.g. Anaconda.org

This could be easy to implement: 

- We just need to serve the repodata from the original location
- Download & forward the packages upon request

**Comment by adriendelsalle** [comment]
Great!

Definitely a *must* have for private compagnies using conda/mamba behind a corporate proxy.

You only have then to configure your `.condarc` to use this server instead of public hosted ones, after having whitelisted the proxied repo urls for the Quetz server host.

**Comment by wolfv** [comment]
We have this now :)
