### ISSUE TITLE
Quetz frontend lacking Content-Type header for api-keys

### ISSUE THREAD

**Issue by riccardoporreca** [mamba-org/quetz#539]
The issue can be easily reproduced using Docker image `mambaorg/quetz:v0.4.4`, as follows

```bash
echo '                       
[general]
frontend_dir = "/quetz-frontend"

[sqlalchemy]
database_url = "sqlite:///./quetz.sqlite"

[session]
# openssl rand -hex 32
secret = "b72376b88e6f249cb0921052ea8a092381ca17fd8bb0caf4d847e337b3d34cf8"
https_only = false
' > ~/quetz-test/config.toml
```

```bash
docker run --rm -v ~/quetz-test:/quetz-deployment mambaorg/quetz:v0.4.4 quetz create --dev /quetz-deployment
docker run --rm -v ~/quetz-test:/quetz-deployment -p 8000:8000 mambaorg/quetz:v0.4.4
```

- Browse to http://localhost:8000/api/dummylogin/alice
- Browse to http://localhost:8000/api-keys click "Request API Key" => no key is displayed
 
Inspecting the request hints at the issue
![image](https://user-images.githubusercontent.com/13663564/171300158-199d2b2e-a137-43c1-9f8c-903368c2a345.png)
![image](https://user-images.githubusercontent.com/13663564/171301068-a163253a-9649-41d3-a13b-50e98305ee0a.png)
reside in the lack of `Content-Type` header, which is indeed not specified (although commented out) in

https://github.com/mamba-org/quetz/blob/d63e2f155aa75dfe852b70674b01ab7732d234c2/quetz_frontend/src/views/ApiKeysView.vue#L49-L54

I tested locally by uncommenting the line, and the issue is indeed solved.

**Comment by brichet** [comment]
Thanks @riccardoporreca for pointing out this issue and providing the means to fix it.
It should be fixed with https://github.com/mamba-org/quetz/pull/557

**Comment by wolfv** [comment]
Hi @riccardoporreca thanks for pointing this out. Actually, we do not really maintain the frontend in this repository anymore. The new one is at https://github.com/mamba-org/quetz-frontend

**Comment by riccardoporreca** [comment]
Thanks @wolfv for the pointer, I did see that repository but was not sure whether that was just version relatated somehow to JupyterLab, since it is a fork of https://github.com/jupyterlab-contrib/jupyterlab-app-cookiecutter :)

Given this, do you have any plan to cleanup the `quetz_frontent` within this repo and switching to using [mamba-org/quetz-frontend](https://github.com/mamba-org/quetz-frontend) in the Docker image published to https://hub.docker.com/r/mambaorg/quetz? See https://github.com/mamba-org/quetz/blob/5d4eb9f974da9d1632ef3a7c701f518aa6e7fd0c/Dockerfile#L4-L7
