### ISSUE TITLE
Missing `h11` dep?

### ISSUE THREAD

**Issue by dhirschfeld** [mamba-org/quetz#545]
Installing an editable package with `pip` wants to install `h11` in the `quetz` environment - maybe it needs to also be specified in the [`environment.yml`](https://github.com/mamba-org/quetz/blob/main/environment.yml) file?
```
Collecting h11>=0.8
  Downloading h11-0.12.0-py3-none-any.whl (54 kB)
```

**Comment by wolfv** [comment]
Hmm, not sure if we should add it or wether it's a dependency of ours that needs to add it to their `meta.yaml`?

**Comment by dhirschfeld** [comment]
That's odd - it doesn't seem to be used directly here 🤔 

If it were a dep of anything in the `environment.yml` it would have been installed so I'm not sure what's pulling it in...

**Comment by dhirschfeld** [comment]
Looks like a dep of [`httpcore`](https://github.com/conda-forge/httpcore-feedstock/blob/main/recipe/meta.yaml#L24) which is a dep of [`httpx`](https://github.com/conda-forge/httpx-feedstock/blob/main/recipe/meta.yaml#L26). Not sure why `mamba env create -f environment.yml` wouldn't install a version `pip` was happy with though.

In any case, nothing to do here...
