### ISSUE TITLE
Uploading package with filename not matching package name

### ISSUE THREAD

**Issue by brichet** [mamba-org/quetz#553]
When uploading a package using the API, if the package name does not match the file name, the response status code is 400 :
https://github.com/mamba-org/quetz/blob/d272e615323c7110bfb7356746e66bdaf7658eae/quetz/main.py#L1528-L1535

But at this point the package has already been uploaded, and remains in channel directory.

Is this an expected behavior ?

If the package is expected to stay, perhaps the status code should be different because the request is executed.
If not,the package should be removed.

**Comment by wolfv** [comment]
Yes, the package should be removed. It's faulty.
