### ISSUE TITLE
Quetz REST API can return 'null' in various fields, making OpenAPI-based evaluation fail.

### ISSUE THREAD

**Issue by kuepe-sl** [mamba-org/quetz#563]
Let's have a look at this example that uses the Quetz default channels and test packages:

```json
$ curl -s -X GET --header "X-API-Key: $QUETZ_API_KEY" http://localhost:8000/api/channels/channel0/packages/package0 | jq
{
  "name": "package0",
  "summary": "package 0 summary text",
  "description": "Description of package0",
  "url": null,
  "platforms": null,
  "current_version": null,
  "latest_change": null
}
$ curl -s -X GET --header "X-API-Key: $QUETZ_API_KEY" http://localhost:8000/api/channels/channel0/packages/xtensor | jq
{
  "name": "xtensor",
  "summary": null,
  "description": "Description of xtensor",
  "url": "http://quantstack.net/xtensor",
  "platforms": [
    "linux-64",
    "osx-64"
  ],
  "current_version": "0.16.1",
  "latest_change": "2022-09-29T07:40:55"
}
```

Here it returns `null` in the fields `summary`, `url` and many others.
This violates the OpenAPI specification that can be downloaded from `http://<quetz-server>/openapi.json`, making it impossible to process the responses using OpenAPI-based applications.

As of now, the specification looks like this:

```json
{
  "openapi": "3.0.2",
  "info": {
    "title": "FastAPI", "version": "0.1.0"
  },
  "components": {
    "schemas": {
      "Package": {
        "title": "Package", "type": "object",
        "properties": {
          "name": {
            "title": "The name of package",
            "maxLength": 1500, "pattern": "^[a-z0-9-_\\.]*$",
            "type": "string"
          },
          "summary": {
            "title": "The summary of the package",
            "type": "string"
          },
          "description": {
            "title": "The description of the package",
            "type": "string"
          },
          "url": {
            "title": "project url",
            "type": "string"
          },
          "platforms": {
            "title": "supported platforms",
            "type": "array",
            "items": { "type": "string" }
          },
          "current_version": {
            "title": "latest version of any platform",
            "type": "string"
          },
          "latest_change": {
            "title": "date of latest change",
            "type": "string",
            "format": "date-time"
          }
        }
      },
```

---

What would be the intended approach to solve this issue?

There are two solutions that I have in mind right now, but there may be more:
1. allow *nullable* values in the specification
2. return empty strings instead of `null`

**Comment by wolfv** [comment]
I think allowing `null` would be cleaner. What do you think?

**Comment by kuepe-sl** [comment]
Yeah, that would be my preferred solution as well.

Would you mind having a look at this?
(I had a look at the Quetz source, but I don't see how the OpenAPI spec. is even generated, so I have no clue where to start.)

**Comment by wolfv** [comment]
Can you have a look here? I think some type annotations are just wrong (need to be `Optional[str]` instead of `str`: https://github.com/mamba-org/quetz/blob/ede87315b0e64368e3c9c3c1bf4b527463226efc/quetz/rest_models.py#L186-L206

**Comment by kuepe-sl** [comment]
Specifying `Optional[str]` unfortunately has no effect.

I tried `Optional[str]` at a few other places in the file and the only effect it has, was to remove entries from the `required` list. (for example in `BaseApiKey`)
For the `Package`, no `required` list is generated at all.

According to the [OpenAPI 3.0 documentation at swagger.io](https://swagger.io/docs/specification/describing-parameters/#nullable), a *nullable* parameter is not the same as an *optional* parameter:

> **Note:** `nullable` is not the same as an optional parameter or an empty-valued parameter. `nullable` means the parameter value can be `null`. Specific implementations may choose to map an absent or empty-valued parameter to `null`, but strictly speaking these are not the same thing.

**Comment by wolfv** [comment]
does `str | None` work?

**Comment by kuepe-sl** [comment]
`nullable=True` works!  
Thanks, I will go through the structures and add that where appropriate.
