### ISSUE TITLE
"latest" Docker image broken by #587

### ISSUE THREAD

**Issue by maresb** [mamba-org/quetz#595]
About one day ago, the Quetz Docker image was rebuilt. In this image, SQLAlchemy v2.0.2 is installed. This triggers #587. (This is causing the conda-lock CI to fail https://github.com/conda/conda-lock/issues/338.)

**Comment by janjagusch** [comment]
We made Quetz compatible with SQLAlchemy >=2.0 in [v0.6.0](https://github.com/mamba-org/quetz/releases/tag/v0.6.0). Can you give this another try, please?

**Comment by maresb** [comment]
Yes, it's working, thanks!
