### ISSUE TITLE
Support .conda package format

### ISSUE THREAD

**Issue by digi691** [mamba-org/quetz#599]
Currently Quetz does not support the .conda package.

What is the .conda file format:
https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/packages.html#conda-file-format

conda-forge announced in November of 22' that .conda build infrastructure was ready to ship.
https://conda-forge.org/docs/orga/minutes/2022-11-16.html#

conda-forge has now started to ship some packages only in the .conda format and quetz is unable to mirror them:
https://anaconda.org/conda-forge/conda-libmamba-solver/files

Output below of the files that were mirrored by quetz v0.5.0

```
user@25607cde82fb:/tmp/test_quetz/channels/conda-forge-slim$ find . | more
.
./channeldata.json.bz2
./channeldata.json.gz
./channeldata.json
./index.html.bz2
./index.html.gz
./index.html
./noarch
./noarch/index.html.bz2
./noarch/index.html.gz
./noarch/index.html
./noarch/repodata.json
./noarch/repodata.json.bz2
./noarch/repodata.json.gz
./noarch/conda-libmamba-solver-22.3.0-pyhd8ed1ab_0.tar.bz2
./noarch/conda-libmamba-solver-22.3.1-pyhd8ed1ab_0.tar.bz2
./noarch/conda-libmamba-solver-22.6.0-pyhd8ed1ab_0.tar.bz2
./noarch/conda-libmamba-solver-22.8.1-pyhd8ed1ab_0.tar.bz2
```

**Comment by wolfv** [comment]
Hi, 

this is not exactly correct. Quetz does support the .conda format, but the mirroring doesn't mirror it yet. I think it's just a matter to also look at the `packages.conda` key in the repodata from which we're mirroring. I don't have time to look into this, but a PR would be very appreciated.
