### ISSUE TITLE
Unable to integrate S3 Bucket in Quetz deployment 

### ISSUE THREAD

**Issue by rmittal87** [mamba-org/quetz#676]
Hi Team,

I am doing quetz deployment on Kubernetes using helm charts, Trying to integrate S3 bucket for channels.
In my config.toml file I have specified URL for the S3 but dont know where to specify the bucket name. 
I am able to deploy quetz successfully, but unable to create any channel .

```
    access_key = "<somevalue>"
    secret_key = "<somevalue>"
    url = "URL of the S3"
    region = "<region>"
    bucket_prefix=".." < don't know exactly what will come in prefix and suffix>
    bucket_suffix=".."__
```
When I enter bucket name in bucket_prefix option, I get the following error

```

error_wrapper(
  File "/base-env/lib/python3.8/site-packages/s3fs/core.py", line 140, in _error_wrapper
    raise err
OSError: [Errno 22] The specified bucket is not valid.
```
--
My question is where do we specify bucket name. In case we need multiple channels, how to specify multiple bucket names

**Comment by ivergara** [comment]
#673 got merged to main and a new release is available. Closing this.
