### ISSUE TITLE
Failed package uploads still appear in repodata.json

### ISSUE THREAD

**Issue by ericdill** [mamba-org/quetz#84]
Took me a while to get the s3 backend working. Resulted in lots of failed attempts at uploading. In spite of the package failing to upload due to s3 permission errors, the package still appears in the repodata.json. Quetz should probably be smart enough to not update the repodata.json if the package fails to upload to s3

**Comment by ericdill** [comment]
Another question about the intended usage of the s3 backend: It looks like the implementation is designed as one bucket per channel?

**Comment by wolfv** [comment]
Thanks for this bug report! Very valuable.

**Comment by wolfv** [comment]
should be fixed now, please report if it's still an issue.
