### ISSUE TITLE
Handle repodata patches

### ISSUE THREAD

**Issue by wolfv** [mamba-org/quetz#91]
We need to figure out how repodata patches work, and how we can apply them in quetz.
This is important work, also with regards to the mirroring feature.

For example: should only the "main" server generate the canonical repodata.json (with patches applied) and the mirror servers use the repodata.json from that server, or should each mirror server generate their own repodata with the patches?
And how will that affect the changelog feature? #87 

cc @btel

**Comment by wolfv** [comment]
these are the repodata patches for conda forge, including an explanation how they work: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/tree/master/recipe

**Comment by wolfv** [comment]
this is what a patch file looks like: https://gist.github.com/wolfv/6ba5729e10909334fca8ef47002ea03d

**Comment by benjamb** [comment]
I must admit I'm not 100% on why the patching functionality exists, but to me it feels like quite the hack. Could the API not be extended instead to support some of these operations directly, rather than continuing with this patching method? With regards to mirroring, I would argue in favour of using the canonical repodata.json (not generating in the mirror/proxy).

**Comment by wolfv** [comment]
@benjamb yes, I agree it seems like a hack. Currently the repodata is generated from the packages (the contents of the packages, specifically).

Now, sometimes there are issues such as too tight pinning of dependencies (let's say package `A` pins `ncurses` to `6.1.0`, but `ncurses 6.1.x` is known to be compatible). This can be fixed by patching the repodata.
The other option would be to either rebuild or overwrite package `A` with the better pin, or to change the package `A` to carry the patched info or to apply a repodata patch...

All options are not great for reproducibility, but for practical reasons the conda-forge distribution makes quite frequent use of these repodata patches (even the default channel does it from time to time).

I wonder if there are "solutions" to this in other package managers...

**Comment by btel** [comment]
there is also some more explanation in the conda docs: https://docs.conda.io/projects/conda-build/en/latest/concepts/generating-index.html#repodata-patching

**Comment by wolfv** [comment]
There is a plugin for this now!
