### ISSUE TITLE
Generate current_repodata.json

### ISSUE THREAD

**Issue by wolfv** [mamba-org/quetz#92]
If we want compatibility with conda, we should think about how to generate the current_repodata.json subset. 
This is implemented in conda-build index function in conda and apparently that's also used by the anaconda server implementation (as @beckermr has added some patches there)

https://github.com/conda/conda-build/blob/eae86a43ddf8aaf60ed850a2c54e512320b05a99/conda_build/index.py#L756

**Comment by beckermr** [comment]
You can return the full repo data blob as a stop gap.

**Comment by wolfv** [comment]
yep, that's what we do currently. But if we start to mirror (hypothetically) all of conda-forge, it would be better to have a mechanism in place for this.

**Comment by wolfv** [comment]
@btel could we use a plugin for this as well, similar to the repodata patching?

**Comment by wolfv** [comment]
thanks to @madhur-tandon we have a plugin now for this (which uses the exact same conda-build code).

:tada: :tada: :tada:
